### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by beechovsky** [dmahapatro/grails-actuator-ui#9]
Hi! I cannot seem to implement your plugin, which looks very helpful!

Here is my stacktrace:
`017-06-14 14:11:39,281 - ERROR org.grails.web.errors.GrailsExceptionResolver - OutOfMemoryError occurred when processing request: [GET] /myApp/actuator/dashboard
Java heap space. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:210)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:281)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:115)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:157)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3210)
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at org.grails.web.json.JSONArray.<init>(JSONArray.java:117)
	at org.grails.web.json.JSONTokener.nextValue(JSONTokener.java:331)
	at org.grails.web.json.JSONObject.<init>(JSONObject.java:175)
	at org.grails.web.json.JSONTokener.nextValue(JSONTokener.java:328)
	at org.grails.web.json.JSONObject.<init>(JSONObject.java:175)
	at org.grails.web.json.JSONTokener.nextValue(JSONTokener.java:328)
	at org.grails.web.json.JSONObject.<init>(JSONObject.java:175)
	at org.grails.web.json.JSONTokener.nextValue(JSONTokener.java:328)
	at org.grails.web.json.JSONObject.<init>(JSONObject.java:175)
	at org.grails.web.json.JSONTokener.nextValue(JSONTokener.java:328)
	at org.grails.web.json.JSONObject.<init>(JSONObject.java:175)
	at org.grails.web.json.JSONTokener.nextValue(JSONTokener.java:328)
	at org.grails.web.json.JSONObject.<init>(JSONObject.java:175)
	at org.grails.web.json.JSONTokener.nextValue(JSONTokener.java:328)
	at org.grails.web.json.JSONObject.<init>(JSONObject.java:175)
	at org.grails.web.json.JSONTokener.nextValue(JSONTokener.java:328)
	at org.grails.web.json.JSONObject.<init>(JSONObject.java:175)
	at org.grails.web.json.JSONTokener.nextValue(JSONTokener.java:328)
	at org.grails.web.json.JSONObject.<init>(JSONObject.java:175)
	at org.grails.web.json.JSONTokener.nextValue(JSONTokener.java:328)
	at grails.converters.JSON.parse(JSON.java:251)
	at grails.converters.JSON$parse$0.call(Unknown Source)
	at org.grails.plugins.actuator.ui.ActuatorDashboardController.parsedEndpointResponse(ActuatorDashboardController.groovy:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

Here is my configuration of your plugin:

In build.gradle:

`repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
    maven {
        credentials {
            username "our username"
            password "our password"
        }
        url "https://repodev.our.company/artifactory/repo/"
    }
    maven {
        url  "http://dl.bintray.com/dmahapatro/plugins"
    }
}

dependencies {
    ...
    compile "org.springframework.boot:spring-boot-starter-actuator"
    compile "org.grails.plugins:actuator-ui:1.1"
    ...
}`
application.yml:

`grails:
    profile: web
    spring:
        transactionManagement:
            proxies: false
        actuator:
            gravatar:
                disabled: true`

application.groovy:
`grails {
    plugin {
        databasemigration {
            changelogLocation = "database"
        }

        springsecurity {
            logout {
                postOnly = false
            }

            securityConfigType = "Annotation"

            controllerAnnotations {
                staticRules = [
                    [pattern:'/actuator/**',                    access:['permitAll']],
                    [pattern:'/actuatordashboard/**',           access:['permitAll']],
                    [pattern:'/actuator:actuatordashboard/**',  access:['permitAll']]
                ]
            }
        }
    }
}`

**Comment by beechovsky** [comment]
I believe I've found the cause of the Memory Leak.

The above stacktrace was from running on my local machine, but when I deploy my app's war to a Tomcat app server i get the following error:
`org.grails.web.json.JSONException
Message
Error parsing JSON
Caused by
Unterminated string at character 23963 of {"profiles":["production","web"],"SecurityConfig":...
Last Line:
{"name":"grailsDispatcherServlet","J2EEServer":"none","J2EEApplication":"none","WebModule":"//localhost/spar##3.00.682","j2eeType":"Servlet"},"keyPropertyListString":"j2eeType=Servlet,WebModule=//localhost/spar##3.00.682,name=grailsDispatcherServlet,J2EEApplication=none,J2EEServer=none","`

It looks like there's an open " at the end of the parsed JSON.

Thanks!

**Comment by dmahapatro** [comment]
@beechovsky Apologize for not being on top of this. I believe the above exception is related to Spring Boot in general, correct me if I am wrong.

Please note, I will not be able to immediately jump onto this issue but if there is a resolution then a PR is definitely welcomed. :)

**Comment by firebiird** [comment]
I'm having the same issue, I've tracked it down to when something is going through the parsedEndpointResponse and the response returns an incomplete JSON it will never return. The actuator/env endpoint for me is generating the following : 

`{"profiles":["development","web"],"server.ports":{"local.server.port":8080},"AuditConfig":{"grails":{"plugin":{"auditLog":{"verbose":true,"defaultIgnore":["version","lastUpdated","lastUpdatedBy"],"logFullClassName":false,"transactional":false,"defaultMask":["password"],"logIds":true,"defaultActor":"SYS","auditDomainClassName":"languagelessons.AuditTrail","stampEnabled":true,"stampTimestamp":true,"nonVerboseDelete":false,"sessionAttribute":"","actorKey":"","actorClosure":{"delegate":{"grailsApplication":{"classLoader":{"parent":{"parent":{"parent":null,"urls":["file:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/sunec.jar","file:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/nashorn.jar","file:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/cldrdata.jar","file:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/jfxrt.jar","file:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/dnsns.jar","file:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/localedata.jar","file:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar","file:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar","file:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/jaccess.jar","file:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/zipfs.jar","file:/System/Library/Java/Extensions/MRJToolkit.jar"]},"urls":["file:/Users/leewilliams/projects/languagelessons/src/main/resources","file:/Users/leewilliams/projects/languagelessons/grails-app/views/","file:/Users/leewilliams/projects/languagelessons/grails-app/i18n/","file:/Users/leewilliams/projects/languagelessons/grails-app/conf/",  .... REMOVED FOR CLARITY ....... "file:/Users/leewilliams/.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-mimetypes/3.3.1/7ad7df939804408e00313ef2116b8150b5c109ec/grails-plugin-mimetypes-3.3.1.jar","file:/Users/leewilliams/.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-validation/3.3.1/3168f2575449d8900414add03cba436b634813b3/grails-plugin-validation-3.3.1.jar",`

Don't know why the endpoint is not generating the rest of the JSON, I thought maybe there is an output limit perhaps??

**Comment by annechou** [comment]
Seeing the same error using this plugin in a Grails 3.2.10 application.  Any solutions for this?

**Comment by mikemassa84** [comment]
I believe the problem is due to the response of the /env endpoint being too large to fit into a String.
